Class {
	#name : 'HSTrainer',
	#superclass : 'HSPlantServiceAgent',
	#traits : 'TCMLocated',
	#classTraits : 'TCMLocated classTrait',
	#instVars : [
		'count'
	],
	#category : 'HideOrShareModel',
	#package : 'HideOrShareModel'
}

{ #category : 'control' }
HSTrainer >> teach [
	"Goes to see a horticulturist and increases his level of detection / decreases his detection threshold (by ...%)"

	
]
